#!/usr/bin/env python3
"""Render the per-cell Kubernetes baseline from cell contracts.

Config Sync reads plain YAML from git — it does not template. So the quota
numbers declared in a cell contract are rendered into committed manifests here,
and CI fails if the committed tree does not match what the contracts produce
(`make render-check`). That keeps one source of truth without giving up
Config Sync's "what is in git is what is in the cluster" property.

    python3 scripts/render_platform.py            # write
    python3 scripts/render_platform.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

HEADER = "# Generated by scripts/render_platform.py from {source}. Do not edit.\n"


def namespace(cell: dict) -> str:
    return "app"


def render(cell: dict, source: str) -> str:
    ns = namespace(cell)
    quotas = cell["gke"]["quotas"]

    docs = [
        {
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {
                "name": ns,
                "labels": {
                    "venture": cell["venture"],
                    "cell": cell["cell"],
                    "env": cell["env"],
                    # Pod Security Admission. `restricted` is the strictest
                    # built-in profile: no privilege escalation, no host
                    # namespaces, non-root only.
                    "pod-security.kubernetes.io/enforce": "restricted",
                    "pod-security.kubernetes.io/audit": "restricted",
                    "pod-security.kubernetes.io/warn": "restricted",
                },
            },
        },
        {
            "apiVersion": "v1",
            "kind": "ResourceQuota",
            "metadata": {"name": "cell-quota", "namespace": ns},
            "spec": {
                "hard": {
                    "requests.cpu": quotas["cpu"],
                    "requests.memory": quotas["memory"],
                    # Limits are set to twice requests: enough headroom for
                    # bursty workloads, not so much that the quota stops
                    # bounding the blast radius of a runaway deployment.
                    "limits.cpu": str(int(quotas["cpu"]) * 2),
                    "pods": quotas["pods"],
                }
            },
        },
        {
            # Default-deny. Every allow rule after this is an explicit,
            # reviewable decision; without it, a namespace is flat.
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "default-deny-all", "namespace": ns},
            "spec": {"podSelector": {}, "policyTypes": ["Ingress", "Egress"]},
        },
        {
            # DNS must be allowed back or every pod in the namespace fails to
            # resolve anything, which is the classic way a default-deny rollout
            # takes down a cluster.
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "allow-dns-egress", "namespace": ns},
            "spec": {
                "podSelector": {},
                "policyTypes": ["Egress"],
                "egress": [
                    {
                        "to": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "kube-system"}}}],
                        "ports": [
                            {"protocol": "UDP", "port": 53},
                            {"protocol": "TCP", "port": 53},
                        ],
                    }
                ],
            },
        },
        {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {"name": "allow-ingress-from-gateway", "namespace": ns},
            "spec": {
                "podSelector": {"matchLabels": {"app.kubernetes.io/component": "web"}},
                "policyTypes": ["Ingress"],
                "ingress": [
                    {
                        "from": [{"namespaceSelector": {"matchLabels": {"kubernetes.io/metadata.name": "gateway"}}}],
                        "ports": [{"protocol": "TCP", "port": 8080}],
                    }
                ],
            },
        },
        {
            # The Kubernetes half of Workload Identity: this service account is
            # what modules/database grants secret access to.
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "app", "namespace": ns},
        },
    ]

    body = yaml.safe_dump_all(docs, sort_keys=False, default_flow_style=False)
    return HEADER.format(source=source) + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", type=pathlib.Path)
    parser.add_argument("--check", action="store_true", help="fail if committed output is stale")
    args = parser.parse_args()

    stale: list[str] = []
    written = 0

    for cell_file in sorted((args.root / "ventures").glob("*/cells/*.yaml")):
        with cell_file.open() as fh:
            cell = yaml.safe_load(fh)

        source = str(cell_file.relative_to(args.root))
        content = render(cell, source)

        out_dir = args.root / "platform" / "cells" / cell["venture"] / cell["cell"]
        out_file = out_dir / "baseline.yaml"

        if args.check:
            if not out_file.exists() or out_file.read_text() != content:
                stale.append(str(out_file.relative_to(args.root)))
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            out_file.write_text(content)
            written += 1

    if args.check:
        if stale:
            print("Rendered platform manifests are stale:\n", file=sys.stderr)
            for path in stale:
                print(f"  ✗ {path}", file=sys.stderr)
            print("\nRun `make render` and commit the result.\n", file=sys.stderr)
            return 1
        print("✓ platform manifests match the cell contracts")
        return 0

    print(f"✓ rendered {written} cell baseline(s) into platform/cells/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
